# Borrowed from klayoutmattias: https://github.com/lightwave-lab/klayout/blob/pymod/.travis.yml
language: python
python: '3.6'
os: linux

# klayout builds from source so this saves 15 minutes on subsequent jobs
cache: pip

install:
  - pip install -r requirements-test.txt
  - pip install .
script:
  - DOCKER=1 pytest tests

deploy:
  provider: pypi
  user: atait
  password:
    secure: Unsnt3R33zIjxVwVu2kORQjkruJ8ZW9USc88Vpy0iBTcv4QfbWkTlXK0vQs1RqzLt0lylfooteaF4gRfqQFIYp0ETFpFh3NLmqKHQLKU6oiuEhyRPQyqo3NwGHx8/t5RSmUQvbC7XUeSdpU8J3ldwE7nmSI8WNlGXOU3Vm8COsg1w2+27Qn29ViAGRDRCOSKE/eg4qb5Seaoih5GFWjnym6xnQ4CxckxevEpZG2XM9MUH5pcRgJvm2d/j/gupk1QCzbKtUldR12/r47a7Dqh8yaVKQXQUWH/OjpnsuPI58qu0n/MMnUbTnqtCCRhHzh6yPDKP24wJIxGj8d1OTWP5eUacIhiA72g9YJ5vABARYk6zaC3eG9GIdxJV8R7/HFt8bcl/UbrJMPkFJ/28YdQqltKvGmjA4AdBZrhHV24bYS+4aLya94gcEOnjVZLPlXdXnGGNoSICOs6ISbynI7/PXWmRqHL1OCwl/rm57TfYtOgpVxC6ioJ1841y5DX+GxbD+RmWO9N638GxErdKsnCdJXQR5/sQIjl9SyZTn/tY4AsveegUe0KktrFbtlcyCd8vXeieSgeTvtOrQBNMNEGpt1F8ZfAiqZtYN4ECPs208WzNt271ZdLqEgskN+NO3uUbOw+AZWnvPf0dA1aRQ4p6WXiGCQ6a1rR1lb9jB90MuI=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    branch: master
